######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 3 13:16:00 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += centwin.h mainwin.h
SOURCES += centwin.cc main.cc mainwin.cc
