######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 7 11:34:24 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += helloqt.cc
