######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 16 16:26:23 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myWidget.h
SOURCES += main.cpp myWidget.cpp
