######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 9 13:17:08 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += mywindow.cc textedit.cc
