######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 5 11:20:53 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += spinbox.cc
