######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 17 13:39:54 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myDialog.h
SOURCES += main.cc mydiolag.cpp
