######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 6 09:46:30 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywidget.h
SOURCES += main.cc mywidget.cc
