######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 7 10:13:15 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mydialog.h mywidget.h
SOURCES += main.cc mydialog.cc mywidget.cc
