######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 23 15:40:55 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mywindow.h
SOURCES += main.cc mywindow.cc
QT+=phonon
