######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 17 13:33:32 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myDialog.h myWidget.h
SOURCES += main.cpp myDialog.cpp myWidget.cpp
