######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 16 14:41:04 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myWidget.h
SOURCES += main.cpp myWidget.cpp
