######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 17 11:46:24 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myDialog.h
SOURCES += main.cpp myDialog.cpp
