######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 21 13:10:45 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += model.h student.h studentdlg.h window.h
SOURCES += main.cc model.cc student.cc studentdlg.cc window.cc
