######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 20 12:16:21 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cc mainwindow.cc
