######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 17 15:06:24 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myDialog.h myWidget.h
SOURCES += main.cpp mydiolag.cpp myWidget.cpp
