######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 30 12:18:17 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += msg.h MyAgent.h MyLoginDlg.h MyMainWindow.h MyChatDlg.h
SOURCES += main.cc MyAgent.cc MyLoginDlg.cc MyMainWindow.cc MyChatDlg.cc
QT += network
