######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 5 10:54:55 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hellobutton.cc
